### ISSUE TITLE
Unspecified exception in System.IO.FileStream.ValidateFileHandle

### ISSUE THREAD

**Issue by laurentprudhon** [laurentprudhon/nlptextdoc#12]
An exception is sometimes thrown in : 

at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at nlptextdoc.text.document.NLPTextDocumentWriter.WriteToFile(NLPTextDocument doc, String path)
   at nlptextdoc.extract.html.WebsiteTextExtractor.WebCrawler_PageCrawlCompletedAsync(Object sender, PageCrawlCompletedArgs e)

Example websites to reproduce this bug : 

https://www.montepaschi-banque.fr/fr/- after 216 pages
https://www.arkea.com/ - after 586 pages, 858 pages

**Comment by laurentprudhon** [comment]
Failed to reproduce : will be replaced by more useful issues with a detailed stack trace in further tests if necessary thanks to the new exceptions file.
