### ISSUE TITLE
ParseInt32 exception at HtmlDocumentConverter.VisitTableHeaderOrCell

### ISSUE THREAD

**Issue by laurentprudhon** [laurentprudhon/nlptextdoc#14]
This exception occured  while extracxting https://www.empruntis.com/epargne/ around page 1099 : 

at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at nlptextdoc.extract.html.HtmlDocumentConverter.VisitTableHeaderOrCell(IElement htmlElement)
   at nlptextdoc.extract.html.HtmlDocumentConverter.VisitChildNodes(INode parentNode)
   at nlptextdoc.extract.html.HtmlDocumentConverter.VisitTableRow(IElement htmlElement)
   at nlptextdoc.extract.html.HtmlDocumentConverter.VisitChildNodes(INode parentNode)
   at nlptextdoc.extract.html.HtmlDocumentConverter.VisitOtherHtmlElement(IElement htmlElement)

**Comment by laurentprudhon** [comment]
Fixed
