### ISSUE TITLE
Fatal exception while crawling : Index was outside the bounds of the array

### ISSUE THREAD

**Issue by laurentprudhon** [laurentprudhon/nlptextdoc#2]
>>> https://www.boursorama.com/

Time    | Pages | Errors | Download   | Disk       | Parsing | Convert |
0:02:18 |   322 |     0  |   199,0 Mb |     2,8 Mb | 0:05:54 | 0:24:00 |fatal: Error occurred during processing of page [https://www.boursorama.com/patrimoine/immobilier/petites-annonces-bien-ici?target=https%3A//www.bienici.com/annonce/ag753735-180577552]
fatal: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at nlptextdoc.extract.html.WebsiteTextExtractor.WebCrawler_ShouldCrawlPageLinks(CrawledPage crawledPage, CrawlContext crawlContext) in C:\Users\laure\OneDrive\Dev\C#\nlptextdoc\nlptextdoc.extract\html\WebsiteTextExtractor.cs:line 157
   at Abot.Crawler.WebCrawler.ShouldCrawlPageLinks(CrawledPage crawledPage) in C:\Users\laure\OneDrive\Dev\C#\nlptextdoc\nlptextdoc.extract.dependencies\Abot\Crawler\WebCrawler.cs:line 796
   at Abot.Crawler.WebCrawler.ProcessPage(PageToCrawl pageToCrawl) in C:\Users\laure\OneDrive\Dev\C#\nlptextdoc\nlptextdoc.extract.dependencies\Abot\Crawler\WebCrawler.cs:line 689

>>> Crawl of https://www.boursorama.com/ completed with error: Index was outside the bounds of the array.

**Comment by laurentprudhon** [comment]
Fixed
