### ISSUE TITLE
Invalid file path generated when URL contains % encoded char codes or multiple dots

### ISSUE THREAD

**Issue by laurentprudhon** [laurentprudhon/nlptextdoc#26]
La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte : 'C:\Users\laure\Desktop\nlptextdoc-data-201908\fr.wikipedia.org\wiki\Cat%C3%A9gorie:Portail:Finance'
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at nlptextdoc.extract.html.WebsiteTextExtractor.WebCrawler_PageCrawlCompletedAsync(Object sender, PageCrawlCompletedArgs e) in C:\Users\laure\OneDrive\Dev\C#\nlptextdoc\nlptextdoc.extract\html\WebsiteTextExtractor.cs:line 445

**Comment by laurentprudhon** [comment]
Error while processing the page : https://fr.wikipedia.org/wiki/Cat%C3%A9gorie:Portail:Entreprises/Articles_li%C3%A9s

La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte : 'C:\Users\laure\Desktop\nlptextdoc-data-201908\fr.wikipedia.org\wiki\Cat%C3%A9gorie:Portail:Entreprises'
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at nlptextdoc.extract.html.WebsiteTextExtractor.WebCrawler_PageCrawlCompletedAsync(Object sender, PageCrawlCompletedArgs e) in C:\Users\laure\OneDrive\Dev\C#\nlptextdoc\nlptextdoc.extract\html\WebsiteTextExtractor.cs:line 445

**Comment by laurentprudhon** [comment]
Error while processing the page : https://fr.wikipedia.org/wiki/Voir_Venise.../...Et_mourir

Could not find file 'C:\Users\laure\Desktop\nlptextdoc-data-201908\fr.wikipedia.org\wiki\Voir_Venise...\...Et_mourir.nlp.txt'.
   at System.IO.FileInfo.get_Length()
   at nlptextdoc.extract.html.WebsiteTextExtractor.WebCrawler_PageCrawlCompletedAsync(Object sender, PageCrawlCompletedArgs e) in C:\Users\laure\OneDrive\Dev\C#\nlptextdoc\nlptextdoc.extract\html\WebsiteTextExtractor.cs:line 445
